[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor="#d33682"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"

[general]
browser.gatherUsageStats = false

